### ISSUE TITLE
PermissionError:

### ISSUE THREAD

**Issue by odemo** [Kvixen/Simulix#29]
I am trying to run simulix.py on a zipped model from Matlab Simulink with following command:
python Simulix.py crane.zip (crane.zip is located in the same folder as simulix)

The result is as follows:
Traceback (most recent call last):
  File "Simulix.py", line 85, in <module>
    main()
  File "Simulix.py", line 49, in main
    rmtree(args.p)
  File "C:\Program Files (x86)\Python37-32\lib\shutil.py", line 516, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Program Files (x86)\Python37-32\lib\shutil.py", line 395, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Program Files (x86)\Python37-32\lib\shutil.py", line 395, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Program Files (x86)\Python37-32\lib\shutil.py", line 395, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Program Files (x86)\Python37-32\lib\shutil.py", line 400, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Program Files (x86)\Python37-32\lib\shutil.py", line 398, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 5] Access is denied: 'C:\\Simulix\\.git\\objects\\pack\\pack-0bc701e4e3fa698c4ae0d453a19465eec7da6f91.idx'

Any idea what can be wrong?

**Comment by Kvixen** [comment]
The path you're trying to build inside will always get deleted when Simulix runs. Try to delete the folder you're generating your FMU in and trying again. Seems like something in that folder currently is in use, such as if you have generated an FMU before and currently is running it in some program. You could always try to use a different build path by supplying the -p <path> argument for another folder.

**Comment by odemo** [comment]
I am running Simulix.py from C:\Simulix folder with the FMU in a different folder, but still the whole Simulix folder gets deleted if I remove the read-only on the idx file.

**Comment by Kvixen** [comment]
I would recommend adding the Simulix directory to your path and running Simulix from where you want to build the fmu/where the ZIP is located. I'm working on a fix on the removing folders part as that is not intended behavior.
